package com.example.fitflow;

import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;

@Entity(tableName = "workout_logs",
        foreignKeys = @ForeignKey(entity = User.class,
                                  parentColumns = "id",
                                  childColumns = "userId",
                                  onDelete = ForeignKey.CASCADE),
        indices = {@Index(value = "date"), @Index(value = "userId")})
public class WorkoutLog {

    @PrimaryKey(autoGenerate = true)
    public int id;

    public long date; // Store as timestamp (milliseconds since epoch)
    public int durationMinutes;
    public int caloriesBurned;
    public int exercisesCompleted;
    public int userId; // Foreign key to User table

    // Constructor
    public WorkoutLog(long date, int durationMinutes, int caloriesBurned, int exercisesCompleted, int userId) {
        this.date = date;
        this.durationMinutes = durationMinutes;
        this.caloriesBurned = caloriesBurned;
        this.exercisesCompleted = exercisesCompleted;
        this.userId = userId;
    }

    // Getters - Room uses these, and they are good practice
    public int getId() {
        return id;
    }

    public void setId(int id) { // Setter for ID might be needed if not autogenerated in some scenarios, though less common with autogenerate
        this.id = id;
    }

    public long getDate() {
        return date;
    }

    public void setDate(long date) {
        this.date = date;
    }

    public int getDurationMinutes() {
        return durationMinutes;
    }

    public void setDurationMinutes(int durationMinutes) {
        this.durationMinutes = durationMinutes;
    }

    public int getCaloriesBurned() {
        return caloriesBurned;
    }

    public void setCaloriesBurned(int caloriesBurned) {
        this.caloriesBurned = caloriesBurned;
    }

    public int getExercisesCompleted() {
        return exercisesCompleted;
    }

    public void setExercisesCompleted(int exercisesCompleted) {
        this.exercisesCompleted = exercisesCompleted;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }
}
